{{/*
=============================================================================
ServiceAccount - Identity for the pods
=============================================================================
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-service.serviceAccountName" . }}
  labels:
    {{- include "node-service.labels" . | nindent 4 }}
  annotations:
    # Vault Kubernetes auth
    {{- if eq (include "node-service.vaultEnabled" .) "true" }}
    vault.hashicorp.com/agent-inject: "true"
    {{- end }}
automountServiceAccountToken: true
