{{/*
=============================================================================
ServiceAccount - Identity for the pods
=============================================================================
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-service.serviceAccountName" . }}
  labels:
    {{- include "node-service.labels" . | nindent 4 }}
automountServiceAccountToken: true
