name: ''
service: ''
type: 'api'

image:
  tag: 'latest'
  pullPolicy: IfNotPresent

vault:
  enabled: null

ingress:
  enabled: true

size: 'M'

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

config: {}
